apiVersion: v1
kind: ConfigMap
metadata:
  name: qotd-web-loggers
  namespace: qotd
data:
  incident.json: |
    {
        "id": "incident",
        "name": "Simulated incident record",
        "template": "Disk status notifier: code=D{{v1}} dstepid={{v2}} vd={{user}}",
        "fields": {
            "v1": {
                "type": "randomInt",
                "min": 1000,
                "max": 9999
            },
            "v2": {
                "type": "randomInt",
                "min": 1000,
                "max": 9999
            },
            "user": {
                "type": "userName"
            }
        },
        "repeat": {
            "mean": 13000,
            "stdev": 200,
            "min": 11000,
            "max": 15000
        }
    }

  heartbeat.json: |
    {
      "id": "heartbeat",
      "name": "A regular log message indicating the health with a simple status.",
      "template": "Web pulse status: {{STATUS}}",
      "fields": {
          "STATUS": {
              "type": "pickWeighted",
              "options": [
                  { "value": "GOOD", "weight": 8 },
                  { "value": "POOR", "weight": 2 }
              ]            
          }
      },
      "repeat": {
          "mean": 4000,
          "stdev": 1000,
          "min": 3000,
          "max": 5000
      }
    }

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: qotd-web
  namespace: qotd
  labels:
    app: qotd
    tier: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qotd-web
  template:
    metadata:
      labels:
        app: qotd-web
    spec:
      volumes:
        - name: qotd-web-loggers
          configMap:
            name: qotd-web-loggers
            defaultMode: 420
      restartPolicy: Always
      containers:
        - name: qotd-web
          image: registry.gitlab.com/quote-of-the-day/qotd-web:3.0.0
          imagePullPolicy: Always
          volumeMounts:
            - name: qotd-web-loggers
              readOnly: true
              mountPath: /app/loggers
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
            - name: svc
              containerPort: 8080
              protocol: TCP
          env:
            - name: LOCAL_LOGGING
              value: "false"
            - name: ENABLE_INSTANA
              value: "false"
            - name: QUOTE_SVC
              value: "qotd-quote.qotd.svc.cluster.local:3001"
            - name: AUTHOR_SVC
              value: "qotd-author.qotd.svc.cluster.local:3002"
            - name: RATING_SVC
              value: "qotd-rating.qotd.svc.cluster.local:3004"
            - name: PDF_SVC
              value: "qotd-pdf.qotd.svc.cluster.local:3005"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              cpu: "50m"
              memory: "200Mi"
            limits:
              cpu: "200m"
              memory: "800Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: qotd-web
  namespace: qotd
  labels:
    app: qotd
    tier: web
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: qotd-web
---
apiVersion: v1
kind: Service
metadata:
  name: qotd-web-svc
  namespace: qotd
  labels:
    app: qotd
    tier: web
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: svc
  selector:
    app: qotd-web
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: qotd-web
  namespace: qotd
  labels:
    app: qotd
    tier: web
spec:
  subdomain: ''
  to:
    kind: Service
    name: qotd-web
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: qotd-web-svc
  namespace: qotd
  labels:
    app: qotd
    tier: web
spec:
  subdomain: ''
  to:
    kind: Service
    name: qotd-web-svc
    weight: 100
  port:
    targetPort: svc
  wildcardPolicy: None


