apiVersion: apps/v1
kind: Deployment
metadata:
  name: qotd-quote
  namespace: {{ APP_NAMESPACE }}
  labels:
    app: qotd
    tier: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: qotd-quote
  template:
    metadata:
      labels:
        app: qotd-quote
    spec:
      restartPolicy: Always
      containers:
        - name: qotd-quote
          image: registry.gitlab.com/quote-of-the-day/quote-service/v4.0.0:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          env:
            - name: LOG_LEVEL
              value: "INFO"
            - name: ENABLE_INSTANA
              value: "{{ .Values.enableInstana }}"
            - name: ANOMALY_GENERATOR_URL
              value: "http://qotd-usecase-{{LOAD_NAMESPACE }}.{{APP_HOST}}/services/quote"
            - name: DB_HOST
              value: "qotd-db.qotd.svc.cluster.local"
            - name: DB_USER
              value: "root"
            - name: DB_PASS
              value: "root"
            - name: DB_NAME
              value: "qotd"
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 60
            timeoutSeconds: 20
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          resources:
            requests:
              cpu: "25m"
              memory: "200Mi"
            limits:
              cpu: "200m"
              memory: "800Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: qotd-quote
  namespace: {{ APP_NAMESPACE }}
  labels:
    app: qotd
    tier: api
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: http
  selector:
    app: qotd-quote
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: qotd-quote
  namespace: {{ APP_NAMESPACE }}
  labels:
    app: qotd
    tier: web
spec:
  to:
    kind: Service
    name: qotd-quote
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
