kind: Deployment
apiVersion: apps/v1
metadata:
  name: qotd-engraving
  namespace: {{ APP_NAMESPACE }}
  labels:
    app: qotd
    tier: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qotd-engraving
  template:
    metadata:
      labels:
        app: qotd-engraving
    spec:
      restartPolicy: Always
      containers:
        - name: qotd-engraving
          image: registry.gitlab.com/quote-of-the-day/qotd-engraving-service/v4.0.0:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3006
              protocol: TCP
          env:
            - name: LOG_LEVEL
              value: "INFO"
            - name: ENABLE_INSTANA
              value: "{{ .Values.enableInstana }}"
            - name: ANOMALY_GENERATOR_URL
{{ if eq .Values.useNodePort true }}
              value: "qotd-usecase.{{ .Values.loadNamespace }}.svc.cluster.local:3012"
{{ else }}
              value: "http://qotd-usecase-{{LOAD_NAMESPACE }}.{{APP_HOST}}/services/engraving"
{{ end }}
            - name: SUPPLY_CHAIN_URL
              value: "{{ .Values.supplyChainUrl }}"
            - name: SUPPLY_CHAIN_SIMULATE
              value: "{{ .Values.supplyChainSimulate }}"
          livenessProbe:
            httpGet:
              path: /health
              port: 3006
            initialDelaySeconds: 60
            timeoutSeconds: 20
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3006
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          resources:
            requests:
              cpu: "25m"
              memory: "200Mi"
            limits:
              cpu: "200m"
              memory: "800Mi"

{{ if eq .Values.useNodePort true }}

---
apiVersion: v1
kind: Service
metadata:
  name: qotd-engraving
  namespace: {{ APP_NAMESPACE }}
  labels:
    app: qotd
    tier: api
spec:
  type: ClusterIP
  ports:
    - port: 3006
      targetPort: 3006
      protocol: TCP
      name: http
  selector:
    app: qotd-engraving

{{ else }}

---
apiVersion: v1
kind: Service
metadata:
  name: qotd-engraving
  namespace: {{ APP_NAMESPACE }}
  labels:
    app: qotd
    tier: api
spec:
  type: ClusterIP
  ports:
    - port: 3006
      targetPort: 3006
      protocol: TCP
      name: http
  selector:
    app: qotd-engraving
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: qotd-engraving
  namespace: {{ APP_NAMESPACE }}
  labels:
    app: qotd
spec:
  to:
    kind: Service
    name: qotd-engraving
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None

{{ end }}
