apiVersion: apps/v1
kind: Deployment
metadata:
  name: qotd-usecase
  namespace: {{ LOAD_NAMESPACE }}
  labels:
    app: qotd
    tier: load
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qotd-usecase
  template:
    metadata:
      labels:
        app: qotd-usecase
    spec:
      containers:
        - name: main
          image: registry.gitlab.com/quote-of-the-day/qotd-usecase-generator/v4.0.0:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3012
              protocol: TCP
          env:
            - name: LOCAL_LOGGING
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: qotd-usecase
  namespace: {{ LOAD_NAMESPACE }}
  labels:
    app: qotd
    tier: load
spec:
  type: ClusterIP
  ports:
    - port: 3012
      targetPort: 3012
      protocol: TCP
      name: http
  selector:
    app: qotd-usecase
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: qotd-usecase
  namespace: {{ LOAD_NAMESPACE }}
  labels:
    app: qotd
    tier: load
spec:
  path: /
  to:
    kind: Service
    name: qotd-usecase
  port:
    targetPort: http

