apiVersion: apps/v1
kind: Deployment
metadata:
  name: qotd-load
  namespace: {{ LOAD_NAMESPACE }}
  labels:
    app: qotd
    tier: load
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qotd-load
  template:
    metadata:
      labels:
        app: qotd-load
    spec:
      containers:
        - name: main
          image: registry.gitlab.com/quote-of-the-day/qotd-load-generator/v4.0.0:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3011
              protocol: TCP
          env:
            - name: LOCAL_LOGGING
              value: "false"
            - name: AUTOSTART
              value: "true"
            - name: QOTD_WEB_HOST
              value: "http://qotd-web-{{ APP_NAMESPACE }}.{{ APP_HOST }}/"
---
apiVersion: v1
kind: Service
metadata:
  name: qotd-load
  namespace: {{ LOAD_NAMESPACE }}
  labels:
    app: qotd
    tier: load
spec:
  type: ClusterIP
  ports:
    - port: 3011
      targetPort: 3011
      protocol: TCP
      name: http
  selector:
    app: qotd-load
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: qotd-load
  namespace: {{ LOAD_NAMESPACE }}
  labels:
    app: qotd
    tier: load
spec:
  path: /
  to:
    kind: Service
    name: qotd-load
  port:
    targetPort: http


