apiVersion: apps/v1
kind: Deployment
metadata:
  name: qotd-usecase
  namespace: qotd-load
  labels:
    app: qotd
    tier: load
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qotd-usecase
  template:
    metadata:
      labels:
        app: qotd-usecase
    spec:
      containers:
        - name: main
          image: registry.gitlab.com/quote-of-the-day/qotd-usecase-generator:2.2.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3012
              protocol: TCP
          env:
            - name: LOCAL_LOGGING
              value: "false"
            - name: QOTD_WEB_SVC
              value: "http://qotd-web-svc-qotd.apps.<YOUR OCP HOST>"
            - name: QOTD_QUOTE_SVC
              value: "http://qotd-quote-svc-qotd.apps.<YOUR OCP HOST>"
            - name: QOTD_AUTHOR_SVC
              value: "http://qotd-author-svc-qotd.apps.<YOUR OCP HOST>"
            - name: QOTD_IMAGE_SVC
              value: "http://qotd-image-svc-qotd.apps.<YOUR OCP HOST>"
            - name: QOTD_RATING_SVC
              value: "http://qotd-rating-svc-qotd.apps.<YOUR OCP HOST>"
            - name: QOTD_PDF_SVC
              value: "http://qotd-pdf-svc-qotd.apps.<YOUR OCP HOST>"
---
apiVersion: v1
kind: Service
metadata:
  name: qotd-usecase
  namespace: qotd-load
  labels:
    app: qotd
    tier: load
spec:
  type: ClusterIP
  ports:
    - port: 3012
      targetPort: 3012
      protocol: TCP
      name: http
  selector:
    app: qotd-usecase
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: qotd-usecase
  namespace: qotd-load
  labels:
    app: qotd
    tier: load
spec:
  path: /
  to:
    kind: Service
    name: qotd-usecase
  port:
    targetPort: http
  tls:
    termination: edge