apiVersion: apps/v1
kind: Deployment
metadata:
  name: qotd-usecase
  namespace: {{ .Values.loadNamespace }}
  labels:
    app: qotd
    tier: load
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qotd-usecase
  template:
    metadata:
      labels:
        app: qotd-usecase
    spec:
      containers:
        - name: main
          image: registry.gitlab.com/quote-of-the-day/qotd-usecase-generator:3.1.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3012
              protocol: TCP
          env:
            - name: LOCAL_LOGGING
              value: "false"
            - name: QOTD_WEB_SVC
              value: "http://qotd-web-svc.qotd.svc.cluster.local:8080"
            - name: QOTD_QUOTE_SVC
              value: "http://qotd-quote-svc.qotd.svc.cluster.local:8081"
            - name: QOTD_AUTHOR_SVC
              value: "http://qotd-author-svc.qotd.svc.cluster.local:8082"
            - name: QOTD_IMAGE_SVC
              value: "http://qotd-image-svc.qotd.svc.cluster.local:8083"
            - name: QOTD_RATING_SVC
              value: "http://qotd-rating-svc.qotd.svc.cluster.local:8084"
            - name: QOTD_PDF_SVC
              value: "http://qotd-pdf-svc.qotd.svc.cluster.local:8085"
            - name: QOTD_ENGRAVING_SVC
              value: "http://qotd-engraving-svc.qotd.svc.cluster.local:8086"
---
apiVersion: v1
kind: Service
metadata:
  name: qotd-usecase
  namespace: qotd-load
  labels:
    app: qotd
    tier: load
spec:
  type: NodePort
  ports:
    - port: 3012
      nodePort: 30012
      name: http
  selector:
    app: qotd-usecase
