apiVersion: apps/v1
kind: Deployment
metadata:
  name: qotd-quote
  namespace: {{ .Values.appNamespace }}
  labels:
    app: qotd
    tier: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qotd-quote
  template:
    metadata:
      labels:
        app: qotd-quote
    spec:
      restartPolicy: Always
      containers:
        - name: qotd-quote
          image: registry.gitlab.com/quote-of-the-day/quote-service/{{ .Values.imageTag }}:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          env:
            - name: LOG_LEVEL
              value: "INFO"
            - name: ENABLE_INSTANA
              value: "{{ .Values.enableInstana }}"
            - name: ANOMALY_GENERATOR_URL
{{ if eq .Values.useNodePort true }}
              value: "qotd-usecase.{{ .Values.loadNamespace }}.svc.cluster.local:3012/services/quote"
{{ else }}
              value: "http://qotd-usecase-{{ .Values.loadNamespace }}.{{ required "Name of anomaly host is required" .Values.host }}/services/quote"
{{ end }}
            - name: DB_HOST
              value: "qotd-db.{{ .Values.appNamespace }}.svc.cluster.local"
            - name: DB_USER
              value: "root"
            - name: DB_PASS
              value: "root"
            - name: DB_NAME
              value: "qotd"
{{ if eq .Values.roksCluster true }}
            - name: INSTANA_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
{{ end }}
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 60
            timeoutSeconds: 20
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          resources:
            requests:
              cpu: "25m"
              memory: "200Mi"
            limits:
              cpu: "200m"
              memory: "800Mi"


{{ if eq .Values.useNodePort true }}

---
apiVersion: v1
kind: Service
metadata:
  name: qotd-quote
  namespace: {{ .Values.appNamespace }}
  labels:
    app: qotd
    tier: api
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: http
  selector:
    app: qotd-quote

{{ else }}

---
apiVersion: v1
kind: Service
metadata:
  name: qotd-quote
  namespace: {{ .Values.appNamespace }}
  labels:
    app: qotd
    tier: api
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: http
  selector:
    app: qotd-quote


{{ end }}
