---
apiVersion: v1
kind: ConfigMap
metadata:
  name: qotd-usecase-library
  namespace: {{ .Values.loadNamespace }}
data:
  readme.txt: |
    This directory contains locally defined scenarios (not part of distribution).

{{ if eq .Values.setDefaultLoggers true }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: qotd-service-defaults
  namespace: {{ .Values.loadNamespace }}
data:
  services_defaults.json: |
    {
        "web": {
            "memHogs": 0,
            "cpuHogs": 0,
            "healthy": true,
            "endpoints": {
                "GET /": {
                    "latency": {
                        "mean": 100,
                        "stdev": 100,
                        "min": 20,
                        "max": 200
                    }
                },
                "GET /random": {
                    "latency": {
                        "mean": 100,
                        "stdev": 100,
                        "min": 20,
                        "max": 200
                    }
                },
                "GET /author/:id": {
                    "latency": {
                        "mean": 100,
                        "stdev": 100,
                        "min": 20,
                        "max": 200
                    }
                },
                "GET /images/:id": {
                    "latency": {
                        "mean": 100,
                        "stdev": 100,
                        "min": 20,
                        "max": 200
                    }
                },
                "GET /pdf/:id": {
                    "latency": {
                        "mean": 100,
                        "stdev": 100,
                        "min": 20,
                        "max": 200
                    }
                },
                "GET /order/:id": {
                    "latency": {
                        "mean": 100,
                        "stdev": 100,
                        "min": 20,
                        "max": 200
                    }
                },
                "POST /order/:id": {
                    "latency": {
                        "mean": 100,
                        "stdev": 100,
                        "min": 20,
                        "max": 200
                    }
                }
            },
            "loggers": {}
        },
        "image": {
            "memHogs": 0,
            "cpuHogs": 0,
            "healthy": true,
            "endpoints": {
                "GET /images/:id": {
                    "latency": {
                        "mean": 100,
                        "stdev": 100,
                        "min": 20,
                        "max": 200
                    }
                }
            },
            "loggers": {}
        },
        "ratings": {
            "memHogs": 0,
            "cpuHogs": 0,
            "healthy": true,
            "endpoints": {
                "GET /ratings/:id": {
                    "latency": {
                        "mean": 100,
                        "stdev": 100,
                        "min": 20,
                        "max": 200
                    }
                }
            },
            "loggers": {
                "heartbeat": {
                    "name": "A regular log message indicating the health with a simple status.",
                    "template": "Heartbeat status: {{"{{"}}STATUS}}",
                    "fields": {
                        "STATUS": {
                            "type": "pickWeighted",
                            "options": [
                                {
                                    "value": "OK",
                                    "weight": 8
                                },
                                {
                                    "value": "SLOW",
                                    "weight": 2
                                }
                            ]
                        }
                    },
                    "repeat": {
                        "mean": 60000,
                        "stdev": 1000,
                        "min": 3000,
                        "max": 5000
                    }
                }
            }
        },
        "pdf": {
            "memHogs": 0,
            "cpuHogs": 0,
            "healthy": true,
            "endpoints": {
                "GET /pdf/:id": {
                    "latency": {
                        "mean": 100,
                        "stdev": 100,
                        "min": 20,
                        "max": 200
                    }
                }
            },
            "loggers": {
                "incident": {
                    "name": "Simulated incident record",
                    "template": "incident error code: E{{"{{"}}v1}} epid={{"{{"}}v2}} dsteuid={{"{{"}}v3}} dstepid={{"{{"}}v4}} vd={{"{{"}}user}} type={{"{{"}}type}} subtype={{"{{"}}subtype}}",
                    "fields": {
                        "v1": {
                            "type": "randomInt",
                            "min": 1000,
                            "max": 9999
                        },
                        "v2": {
                            "type": "randomInt",
                            "min": 1000,
                            "max": 9999
                        },
                        "v3": {
                            "type": "randomInt",
                            "min": 1000,
                            "max": 9999
                        },
                        "v4": {
                            "type": "randomInt",
                            "min": 1000,
                            "max": 9999
                        },
                        "user": {
                            "type": "userName"
                        },
                        "type": {
                            "type": "pick",
                            "options": [
                                "access",
                                "update",
                                "weight"
                            ]
                        },
                        "subtype": {
                            "type": "pick",
                            "options": [
                                "read",
                                "write",
                                "delete"
                            ]
                        }
                    },
                    "repeat": {
                        "mean": 120000,
                        "stdev": 5000,
                        "min": 5000,
                        "max": 20000
                    }
                }
            }
        },
        "author": {
            "memHogs": 0,
            "cpuHogs": 0,
            "healthy": true,
            "endpoints": {
                "GET /authors/:id": {
                    "latency": {
                        "mean": 100,
                        "stdev": 100,
                        "min": 20,
                        "max": 200
                    }
                },
                "GET /images/:id": {
                    "latency": {
                        "mean": 100,
                        "stdev": 100,
                        "min": 20,
                        "max": 200
                    }
                }
            },
            "loggers": {}
        },
        "quote": {
            "memHogs": 0,
            "cpuHogs": 0,
            "healthy": true,
            "endpoints": {
                "GET /quotes/:id": {
                    "latency": {
                        "mean": 100,
                        "stdev": 100,
                        "min": 20,
                        "max": 200
                    }
                }
            },
            "loggers": {}
        },
        "engraving": {
            "memHogs": 0,
            "cpuHogs": 0,
            "healthy": true,
            "endpoints": {
                "POST /order": {
                    "latency": {
                        "mean": 100,
                        "stdev": 100,
                        "min": 20,
                        "max": 200
                    }
                }
            },
            "loggers": {}
        }
    }
{{ end }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qotd-usecase
  namespace: {{ .Values.loadNamespace }}
  labels:
    app: qotd
    tier: load
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qotd-usecase
  template:
    metadata:
      labels:
        app: qotd-usecase
    spec:
      volumes:
        - name: qotd-usecase-library
          configMap:
            name: qotd-usecase-library
            defaultMode: 420
{{ if eq .Values.setDefaultLoggers true }}
        - name: qotd-service-defaults
          configMap:
            name: qotd-service-defaults
            defaultMode: 420
{{ end }}
      containers:
        - name: main
          image: registry.gitlab.com/quote-of-the-day/qotd-usecase-generator/{{ .Values.imageTag }}:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: qotd-usecase-library
              readOnly: true
              mountPath: /app/library
{{ if eq .Values.setDefaultLoggers true }}
            - name: qotd-service-defaults
              readOnly: true
              mountPath: /app/config
{{ end }}
          ports:
            - name: http
              containerPort: 3012
              protocol: TCP
          env:
            - name: LOCAL_LOGGING
              value: "false"
            - name: BRANDING
              value: "{{ .Values.branding }}"

{{ if eq .Values.useNodePort true }}
---
apiVersion: v1
kind: Service
metadata:
  name: qotd-usecase
  namespace: {{ .Values.loadNamespace }}
  labels:
    app: qotd
    tier: load
spec:
  type: NodePort
  ports:
    - port: 3012
      name: http
  selector:
    app: qotd-usecase

{{ else }}

---
apiVersion: v1
kind: Service
metadata:
  name: qotd-usecase
  namespace: {{ .Values.loadNamespace }}
  labels:
    app: qotd
    tier: load
spec:
  type: ClusterIP
  ports:
    - port: 3012
      targetPort: 3012
      protocol: TCP
      name: http
  selector:
    app: qotd-usecase
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: qotd-usecase
  namespace: {{ .Values.loadNamespace }}
  labels:
    app: qotd
    tier: load
spec:
  path: /
  to:
    kind: Service
    name: qotd-usecase
  port:
    targetPort: http

{{ end }}

